### ISSUE TITLE
Nav

### ISSUE THREAD

**Issue by baut0015** [baut0015/web-design-2-independent-project#4]
Hi @JessJodoin my nav disappears when increasing the screen size above 38em 

I would like to know how to make it appear as I used to have it appear but now I don't know why it doesn't :(

**Comment by JessJodoin** [comment]
Your nav isn't showing on the 38em size because of the grid you have set up on your nav

The way I was able to fix it was:
```
  nav {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr 1fr 1fr;
    grid-gap: 1rem;
    text-align: center;
    justify-items: center;
    margin: 0 auto;
  }

  .content {
    display: contents;
    line-height: 50px;
    list-style: none;
  }

```
